### ISSUE TITLE
GoodsApplication 启动失败

### ISSUE THREAD

**Issue by XQCTO** [atn-lyn/lyn-parents#1]
2019-06-26 14:44:06.182  INFO 13828 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2019-06-26 14:44:06.208  INFO 13828 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-06-26 14:44:06.318 ERROR 13828 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field storageClient in com.lyn.common.fastdfs.FastdfsServiceImpl required a bean of type 'com.github.tobato.fastdfs.service.FastFileStorageClient' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'com.github.tobato.fastdfs.service.FastFileStorageClient' in your configuration.

**Comment by lynatn** [comment]
I found this issues，due to the fastDFS was scanned at project startup.  I have modified the scan package config in the GoodsApplication class. now is ok!
![1561736019(1)](https://user-images.githubusercontent.com/51996956/60353744-4088e600-99fd-11e9-94a6-42352ec7480a.png)

Please tell me if you find any questions!
